spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dan_phong_tro}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-version: 8
    baseline-on-migrate: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: hhh262434@gmail.com
    password: zcvvdmjaqtdlzbif
    protocol: smtp
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
    from: ${MAIL_FROM:hhh262434@gmail.com}


aws:
  java:
    v1:
      printLocation: true
      disableDeprecationAnnouncement: true
amazon:
  s3:
    bucketName: ${S3_BUCKET_NAME:phongtrodatn}
    region: ${S3_REGION:us-east-1}
    accessKey: ${S3_ACCESS_KEY:AKIAVVZOONWNYQCET57A}
    secretKey: ${S3_REFRESH_KEY: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}

vnpay:
  tmnCode: 2E4NTINT
  hashSecret: OPZ9E3HHTSYXKVQ0KVZP4B7BABIDB5OK
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#  returnUrl: http://localhost:8080/api/v1/pay/return
  returnUrl: http://localhost:5173/vnpay-return
  ipnUrl: http://localhost:8080/api/v1/pay/ipn
openai:
  api:
    key: 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



logging:
  level:
    org.springframework.messaging: DEBUG
    org:
      springframework:
        messaging:
          simp: DEBUG
    org.springframework.web.socket: DEBUG
#    org.hibernate.SQL: DEBUG         # Log các SQL statement
#    org.flywaydb.core: DEBUG
#    sql: trace
#    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open-api:
  service:
    api-docs: demo
    server: ${SWAGGER_ENDPOINT:http://localhost:8080}
    title: Api
    version: 1.0
jwt:
  accessKey: ${ACCESS_KEY:b270147ff516860aafb4f52818cb149defde2fac57b451fa3b053d24e88b915a}
  refreshKey: ${REFRESH_KEY:b270147ff516860aafb4f52818cb149defde2fac57b451fa3b053d24e88b915a}
  resetKey: ${RESET_KEY:b270147ff516860aafb4f52818cb149defde2fac57b451fa3b053d24e88b915a}